### ISSUE TITLE
[Video] Opening a video in fullscreen crashes the display

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#225] opened 2019-04-30 15:04 UTC
To reproduce:

1. Find a story with a video
2. Play the video
3. Click the fullscreen icon on the video player
4. Notice that the fullscreen display crashes after ~half a second

A good amount of discussion took place on this subject at Ruby by the Bay 2019: https://github.com/rubyforgood/terrastories/issues/24

**Comment by csexton** [comment] 2019-06-01 19:39
Attempted to reproduce this locally and was unable to get a crash.

Branch: master (b1049a2)

Browsers Tested:

| Name | Version |
| ----- | ----- |
| Safari | Version 12.1.1 (14607.2.6.1.1)|
| Google Chrome | Version 74.0.3729.169 (Official Build) (64-bit) |

Any other steps to repo I'd be happy to try 😄

**Comment by mirandawang** [comment] 2019-06-01 20:48
Closing since we haven't been able to reproduce.

**Closed by mirandawang** 2019-06-01 20:48 UTC
Labels: difficulty: intermediate, priority: medium, status: help wanted, type: bug, type: video
