### ISSUE TITLE
[Tests] Test CurriculumStory model

### ISSUE THREAD

**Issue by rgenchev** [Terrastories/terrastories#524] opened 2020-10-01 23:27 UTC
I noticed that there aren't any tests for `CurriculumStory` model. I'd like to add some. Can I work on this?

**Comment by mirandawang** [comment] 2020-10-02 19:08
@rgenchev You are totally welcome to!

**Comment by mirandawang** [comment] 2020-10-02 19:16
@rgenchev I believe this is a duplicate of https://github.com/Terrastories/terrastories/issues/491 , I'll assign you over there! Thanks!

**Closed by mirandawang** 2020-10-02 19:16 UTC
